# Generated by Django 3.0.7 on 2020-07-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelrelation', '0002_auto_20200702_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_address', to='modelrelation.Address'),
        ),
    ]
