# Generated by Django 3.0.7 on 2020-07-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmedia', '0002_auto_20200709_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='file-media'),
        ),
    ]
