# Generated by Django 3.0.7 on 2020-07-09 04:47

from django.db import migrations, models
import staticmedia.models


class Migration(migrations.Migration):

    dependencies = [
        ('staticmedia', '0003_auto_20200709_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to=staticmedia.models.file_path),
        ),
    ]
