# Generated by Django 3.0.7 on 2020-07-03 09:47

from django.db import migrations, models
import modelextra.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelextra', '0002_auto_20200703_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='age',
            field=models.IntegerField(validators=[modelextra.models.validate_my_age]),
        ),
    ]
